dist: trusty
language: python
jobs:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.2"
  - python: "3.3"
  - python: "3.4"
  - python: "3.5"
  - python: "3.6"
  - python: "3.7-dev"
addons:
  apt:
    packages:
    - libaa1
cache: pip
before_install:
- pillow=pillow
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pillow+='<4'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pillow+='<6'; fi
- pyflakes=pyflakes
- if [[ $TRAVIS_PYTHON_VERSION = 2.6 ]]; then pyflakes='pyflakes<2'; fi
- if [[ $TRAVIS_PYTHON_VERSION = 3.[23] ]]; then pyflakes='pyflakes<2'; fi
install:
- pip install --verbose $pillow
- pip install pydiatra $pyflakes
script:
- dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
- PYTHONPATH=$PWD python test/test.py
- LC_ALL=C python setup.py --version
- python -m pydiatra .
- pyflakes .
- python setup.py install
- cd /
- python -c 'import aalib'
- curl -fsS https://pypi.org/simple/aalib/; [ $? -eq 22 ]

# vim:ts=2 sts=2 sw=2 et
