dist: trusty
sudo: false
language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6"
- "3.7-dev"
addons:
  apt:
    packages:
    - libaa1
cache:
  directories:
  - $HOME/.cache
install:
- if [ "$TRAVIS_PYTHON_VERSION" = '2.6' ]; then PILLOW_VERSION=3.4.2; fi
- pip install --verbose pillow${PILLOW_VERSION:+==$PILLOW_VERSION}
- pip install pydiatra pyflakes
script:
- PYTHONPATH=$PWD python test/test.py
- LC_ALL=C python setup.py --version
- python -m pydiatra .
- pyflakes .
- python setup.py install
- cd /
- python -c 'import aalib'

# vim:ts=2 sts=2 sw=2 et
