language: python
python:
- "2.6"
- "2.7"
- "3.2"
- "3.3"
- "3.4"
- "3.5"
- "3.6-dev"
- "3.7-dev"
addons:
  apt:
    packages:
    - libaa1
cache:
  directories:
  - $HOME/.cache
install:
- \[ "$TRAVIS_PYTHON_VERSION" = "3.2" ] || pip install --upgrade pip
- pip install pillow
script:
- python setup.py build
- cp build/lib*/*.py test/
- python test/test.py

# vim:ts=2 sts=2 sw=2 et
