name: CI
on:
- push
- pull_request
jobs:
  main:
    strategy:
      matrix:
        include:
        - python: '2.7'
          os: ubuntu-20.04
        - python: '3.5'
          os: ubuntu-20.04
        - python: '3.6'
          os: ubuntu-20.04
        - python: '3.7'
          os: ubuntu-20.04
        - python: '3.8'
          os: ubuntu-20.04
        - python: '3.9'
          os: ubuntu-20.04
        - python: '3.10'
          os: ubuntu-22.04
        - python: '3.10'
          os: macos-11
        - python: '3.11'
          os: ubuntu-22.04
        - python: '3.12-dev'
          os: ubuntu-22.04
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3
    - name: set up APT
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
      if: startsWith(matrix.os, 'ubuntu-')
    - name: set up Python ${{matrix.python}}
      if: matrix.python != '2.7'
      uses: actions/setup-python@v4
      with:
        python-version: ${{matrix.python}}
    - name: set up Python 2.7 (with APT + get-pip)
      if: matrix.python == '2.7'
      run: |
        sudo apt-get install python-is-python2
        wget https://bootstrap.pypa.io/pip/2.7/get-pip.py
        sudo python get-pip.py
        rm get-pip.py
    - name: set up pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: pip-${{matrix.os}}-python${{matrix.python}}
    - name: install setuptools (if distutils is missing)
      if: env.pythonLocation
      run: |
        if ! [ -d ${{env.pythonLocation}}/lib/python*/distutils/ ]; then
          python -m pip install setuptools
        fi
    - name: install AAlib
      run:
        sudo apt-get install libaa1-dev
      if: startsWith(matrix.os, 'ubuntu-')
    - name: install AAlib
      run: |
        brew install automake
        wget https://downloads.sourceforge.net/aa-project/aalib-1.4rc5.tar.gz
        tar -xzf aalib-*.tar.gz
        cd aalib-*/
        autoreconf -vfi
        wget https://raw.githubusercontent.com/Homebrew/formula-patches/6e23dfb/aalib/1.4rc5.patch
        patch -p1 < 1.4rc5.patch
        rm 1.4rc5.patch
        sed -i~ -e $'1 i\\\n#include <stdlib.h>\\\n#include <string.h>' src/*.c
        ./configure --with-x11-driver=no
        make
        make install
        rm -rf aalib-*
      if: startsWith(matrix.os, 'macos-')
    - name: install Pillow
      run:
        python -m pip install --verbose pillow
    - name: check changelog syntax
      run:
        dpkg-parsechangelog -ldoc/changelog --all 2>&1 >/dev/null | { ! grep .; }
      if: startsWith(matrix.os, 'ubuntu-')
    - name: run smoke test
      run:
        PYTHONPATH=$PWD make -C test smoke-test
    - name: run ABI test
      run:
        PYTHONPATH=$PWD make -C test abi-test
    - name: run pydiatra
      run: |
        python -m pip install pydiatra
        python -m pydiatra -v .
    - name: run pyflakes
      run: |
        python -m pip install pyflakes
        python -m pyflakes .
    - name: check whether setup.py works in the C locale
      run:
        LC_ALL=C python setup.py --version
    - name: install via setup.py
      run: |
        python setup.py install --user
    - name: check import
      run: |
        cd /
        python -c 'import aalib'

# vim:ts=2 sts=2 sw=2 et
